---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
    - 34d3e6567ab79d882ebb0ff81dcd99d041bc425a7ca8ccc9073e612e8094b7fb
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
    exclude_paths:
      - spec/
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
  flog:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.haml"
  - "**.rb"
  - "**.js"
  - "**.md"
  - "**.scss"
exclude_paths:
- app/assets/stylesheets/application/jqcloud.css.scss
- node_modules/**/*
- script/**/*
- tmp/**/*
- vendor/**/*
- .rubocop.yml
