language: ruby
cache: bundler
rvm:
- 2.3.0
env:
  matrix:
  - DB=postgresql
  global:
    secure: BiFwabvcPOzPPN/w6eC2ZwIL7pITFPvAOl0pjHMUWL7OgcjPfqDtiexTjLdWNOm0U7Qg6+lhmiT8sXJv0HzbkBny+O6QUQDcPcwspZximDdbMyefl1GXU+VfS18/1Uphs1L8V2doPJPATaEUNGnQ0qsdB0dgjFNGd+ddAp81tes=
script:
- RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
- psql -c 'create database rayons_test;' -U postgres && npm install -g grunt-cli
