language: ruby
bundler_args: --without development --path=~/.bundle --jobs=4 --retry=3 --deployment
rvm:
  - rbx-2.2.10
env:
  - DB=postgresql
script:
  - grunt && RAILS_ENV=test COVERAGE=true bundle exec rake db:migrate && bundle exec rspec
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - psql -c 'create database rayons_test;' -U postgres && npm install -g grunt-cli && npm install
