version: '3'
volumes:
  postgres:
services:
  db:
    image: postgres:11.4
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: bundle exec puma -p 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
  worker:
    build: .
    command: bundle exec clockwork config/clock.rb
    depends_on:
      - db
