web:
  build: .
  ports:
   - "3000:3000"
  links:
   - memcached
   - postgres
  environment:
    DATABASE_URL: postgres://postgres@postgres:5432
    MEMCACHE_SERVERS: memcached:11211
postgres:
  image: postgres
  environment:
    LC_ALL: C.UTF-8
memcached:
  image: memcached
