version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.0
      - image: postgres:9.4.10
        environment:
          POSTGRES_USER: postgres
    working_directory: ~/rayons
    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -y build-essential nodejs postgresql-client
      - run: bundle install -j4
      - run: bundle exec rake db:create db:migrate RAILS_ENV=test
      - run: bundle exec rake
