version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.0
      - image: postgres:9.4.10
        environment:
          POSTGRES_USER: postgres
    working_directory: ~/rayons
    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -y build-essential nodejs postgresql-client
      - run: bundle install -j4
      - run: bundle exec rake db:create db:migrate RAILS_ENV=test
      - run: bundle exec rake
      - deploy:
          name: Enqueue Deploy Job
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=deploy \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            fi
  deploy:
    docker:
      - image: gordondiggs/rayons-docker-deploy
    working_directory: ~/rayons
    steps:
      - run: if [ "$CIRCLE_BRANCH" != "master" ]; then exit 1; fi
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build --rm -t gordondiggs/rayons:b$CIRCLE_BUILD_NUM .
      - run: docker push gordondiggs/rayons:b$CIRCLE_BUILD_NUM
      - run: ecs-deploy -c default -n rayons-web -i gordondiggs/rayons:b$CIRCLE_BUILD_NUM
      - run: ecs-deploy -c default -n rayons-clockwork -i gordondiggs/rayons:b$CIRCLE_BUILD_NUM
