development:
  adapter: postgresql
  encoding: unicode
  database: rayons_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rayons_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: rayons_production
  adapter: postgresql
  encoding: unicode
  pool: 5
