default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: databas3
  host: db

development:
  <<: *default
  database: rayons_development

test:
  <<: *default
  database: rayons_test

qa:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: 8

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: 16
