default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 
  host: db

development:
  <<: *default
  database: rayons_development

test:
  <<: *default
  database: rayons_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: rayons_production
  adapter: postgresql
  encoding: unicode
  pool: 16
