development:
  adapter: postgresql
  encoding: unicode
  database: rayons_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rayons_test

production:
  adapter: postgresql
  encoding: unicode
  database: rayons_production
